### ISSUE TITLE
completion; use better/complete type parsing

### ISSUE THREAD

**Issue by ruby0x1** [snowkit/atom-haxe#2]
Ported from @jeremyfa coffeescript version, to replace [the existing version](https://github.com/snowkit/atom-haxe/blob/master/lib/completion/provider.js#L158-L160)

**Comment by jeremyfa** [comment]
Currently porting my type parsing code. I don't remove the previous one yet. Just add mine for now.

**Comment by jeremyfa** [comment]
Ported all the parsing/signature utilities that will help improving completion. Will plug these methods when improving the completion itself with type hinting, but this is the story of another issue so I close this one.
