### ISSUE TITLE
incorrect argument highlighting in call tips

### ISSUE THREAD

**Issue by nadako** [snowkit/atom-haxe#20]
When displaying call tips, when cursor is after the `,`, call tip still highlights previous argument:
![](http://take.ms/KdvB6)
However if we add space there, it highlights the current one.
![](http://take.ms/eaGuB)

**Comment by ruby0x1** [comment]
This is related to #15 , where without this above, it becomes much worse to use iirc.

**Comment by ruby0x1** [comment]
This should be fixed btw, let me know if it's not i'll reopen

**Comment by nadako** [comment]
looks good
