### ISSUE TITLE
completion; Cannot complete after \n character in string

### ISSUE THREAD

**Issue by anissen** [snowkit/atom-haxe#23]
![](http://zippy.gfycat.com/FarflungRelievedGannet.gif)

---

Works:

``` haxe
var arr = new Array();
var str = '${arr.|}\ntext';
```

Doesn't work:

``` haxe
var arr = new Array();
var str = 'text\n${arr.|}';
```

**Comment by jeremyfa** [comment]
Seems to be on haxe server side. On the second case, it triggers and `Interp.Invalid_expr` error.

**Comment by nadako** [comment]
Please report that to the haxe repo.

**Comment by nadako** [comment]
(though i'm surprised that haxe supports completion inside interpolated string, that's something :))

**Comment by jeremyfa** [comment]
I noticed another problem (maybe related), if we query haxe server with:

``` haxe
var arr = new Array();
var str = 'text\n${arr.|
```

In other words, without code after the cursor, which works for all the other completion cases, it triggers and `Unclosed string error`.

**Comment by jeremyfa** [comment]
I will file an issue
