### ISSUE TITLE
The "Requirements" section inside readme.md should explict "Haxe" as one of the requirements

### ISSUE THREAD

**Issue by frenetic** [snowkit/atom-haxe#25]
It's not clear that having Haxe is a requirement for this package to work.
Installing this package without this requirement will result on Atom displaying warnings/errors.
Even though it's acceptable to assume that Haxe developers have Haxe installed on their machines, it shouldn't be a "hidden dependence" for this package.

Also, at least for my specific case, I don't have Haxe installed. For now, since Im learning the language, Im using Vagrant/VMs with Haxe.

**Comment by ruby0x1** [comment]
hmm, I'm not sure I understand - The only requirements are listed:

```
requires linter package
requires language-haxe package
requires autocomplete-plus package
```

This package is called "haxe" on atom packages, the other is called "language-haxe" and it's listed as a requirement already?

It should (if you didn't have it installed) pop up a modal message that you have to manually dismiss, and it tells you that you need it:

![screenshot 2015-03-14 10 27 49](https://cloud.githubusercontent.com/assets/236374/6876371/d35ba3dc-d4a9-11e4-9f36-dbcabc3e8394.png)

Am I misunderstanding maybe? :)

**Comment by frenetic** [comment]
Sorry, I was not clear enough. My bad :(

The requirements section should explicit that "You need the Haxe language to be installed on your computer".
if you dont have it installed, you get this errors.

![haxe_dependence](https://cloud.githubusercontent.com/assets/122976/6876532/13b9454a-d4a7-11e4-8969-a1831fb09383.png)

**Comment by ruby0x1** [comment]
Aha, Ok I see - that makes sense, I will amend the requirements.

**Comment by frenetic** [comment]
Thanks :hamster:

**Comment by ruby0x1** [comment]
You should see an update as well but the readme was updated. 
Thanks!
