### ISSUE TITLE
When pressing CTRL+B on a "non-haxe" project, nothing should be displayed to the user

### ISSUE THREAD

**Issue by jeremyfa** [snowkit/atom-haxe#28]
![capture d ecran 2015-03-30 a 18 23 41](https://cloud.githubusercontent.com/assets/164094/6900987/92e60ce4-d70a-11e4-95c1-89527e5081b7.png)

If I want to add the same shortcut for, let's say, building a coffee-script project, the haxe console will show up as well when pressing CTRL+B.

Maybe we should detect that when the selected flow/hxml file is not in the current workspace and if the current edited file is not a haxe/flow/hxml file, the console doesn't show up.

**Comment by ruby0x1** [comment]
It's just meant to be in debug log, maybe you have debug logging enabled?

**Comment by jeremyfa** [comment]
No it's not:

![capture d ecran 2015-03-30 a 21 40 01](https://cloud.githubusercontent.com/assets/164094/6905029/642adc0c-d725-11e4-875b-0ca41f97fa61.png)

**Comment by ruby0x1** [comment]
Then it's just the wrong function call :}
