### ISSUE TITLE
Support for HaxeFlixel (or Project.xml)

### ISSUE THREAD

**Issue by diegomachado** [snowkit/atom-haxe#29]
Hey guys! 

I'm using HaxeFlixel and it would be really awesome to use this package with it. I don't know if this is the cause, but HaxeFlixel uses a Project.xml (instead of an HXML) file to config libraries to be used.

I don't know if it would help, but this sublime plugin can handle it:
https://github.com/clemos/haxe-sublime-bundle

**Comment by jeremyfa** [comment]
Hi, the atom haxe plugin is only focused on haxe-specific features like autocomplete, error linting etc... Haxeflixel is using openFL, which is outside of the scope of this plugin, and should stay outside. However, the haxe plugin is designed to be extended with framework-specific features and it will be definitely possible to handle openFL project format by writing a separate plugin (like what has been done for https://github.com/snowkit/atom-flow). But it is probably not a good idea to attempt to write this plugin at the moment as atom haxe (and flow) plugins are still under heavy development and are likely to change completely in the coming weeks/months.
