### ISSUE TITLE
how to run openfl code

### ISSUE THREAD

**Issue by lewislepton** [snowkit/atom-haxe#30]
hwdy,

this may be simple. but is there a way this can run openfl code at all from within atom?
not seen anything too much on this, except people saying to just do it in console

thanks

**Comment by ruby0x1** [comment]
The way it works is that this package (the haxe package) provides support for and services for haxe specific features only, and serves them outward for other (framework specific) packages to share. Framework specific support (like openfl with lime tools, or flow) are separate packages. 

There is no and will be no openfl support in _this_ plugin, that's not an option. An atom-openfl package must be made that will handle it's own details - and use the services from this package to do the rest of the work. For the service documentation while we are unifying the package code for sublime/atom - see https://github.com/snowkit/atom-haxe/blob/master/SERVICES.md
