### ISSUE TITLE
Auto-completion happens on ; at end of line

### ISSUE THREAD

**Issue by thoughton** [snowkit/atom-haxe#38]
Hi,

I've noticed auto-completion happens after typing the semi-colon (;) at the end of a line/statement.

I realise the user could in theory start typing another statement at that point, but in practice it does not seem very useful to me. In fact I find it quite a hindrance, as it causes me to have to dismiss the pop-up at the end of almost every line.

Perhaps an option in the Settings could let the user specify a list of characters not to auto-complete after?

Thanks!

**Comment by ruby0x1** [comment]
Just curious if that happens with or without some whitespace at the moment?

Like :
`stuff();<complete popup>` 
vs 
`stuff();<whitespace><complete popup>`

**Comment by thoughton** [comment]
Hi, the popup happens without whitespace, and stays visibile if whitespace is then added too.

**Comment by lewislepton** [comment]
aye, i have the same thing. then when you think you have finished the line, press enter to go to the next line, but instead its entered a new piece of auto-completed code

**Comment by thoughton** [comment]
Haven't had a chance to try this yet, but it sounds great - thanks! :)

**Comment by ruby0x1** [comment]
Version 0.8.5 should have it in, Atom will bring it down for you :)

**Comment by thoughton** [comment]
Yep, just tried it. Only gave it a quick test, but seems to work like a charm. :)

**Comment by lewislepton** [comment]
aye. tried it. seems to be working fine now

many thanks
