### ISSUE TITLE
some errors messages are misleading

### ISSUE THREAD

**Issue by lewislepton** [snowkit/atom-haxe#39]
when running thorugh some AS3 tutorials. there have been error messages. but they seem backwards
one such line as an example is this

```
private var _ySpeed:Int;
_ySpeed = 0.05;
```

then when i run the code it pops up with this message:
`Source/Fruit.hx:21: characters 4-18 : Float should be Int`
realistically it should be the other way around like this:
`Source/Fruit.hx:21: characters 4-18 : Int should be Float`

**Comment by ruby0x1** [comment]
No it's actually correct. You're assigning a Float value to an Int storage, it says that _that_ float, should be an Int, which is what the storage expects.

Also these errors come from haxe itself, not the package. The package uses the haxe compiler for any errors you see.
