### ISSUE TITLE
Autocomplete fails to produce completion, "go to definition" fails and the Linter fails (all related)

### ISSUE THREAD

**Issue by prime31** [snowkit/atom-haxe#45]
I finally tracked this one down and got a hack in place for now. The main gist of this is that when the autocomplete server tries to compile the project to get completions, go to definition or lint the project it fails with:

```
Type not found: LuxeApp
```

This happens with all the test and sample projects included with Luxe. Note also that flow builds them just fine. I can only guess this happens due to the replacement tags in the LuxeApp class but I really dont have enough experience with all this to say for sure.

I was able to hack around it by first doing a web build (which gets a LuxeApp class with the replacement tags removed) and then adding the path to the build directory for all haxe compiler calls.

In the haxe-call.js file, I modified the haxe method to have the extra search path:

```
args.push( '-cp' );
args.push( 'bin/web.build/haxe' );
```

Note that this is obviously not a proper fix. I don't know what a proper fix would be for this but I figured I would detail the exact error and what fixes it (finding the LuxeApp class).

**Comment by ruby0x1** [comment]
Try setting the flow file after the first build, since the build also adds that line to the bin/target.build/build.hxml file

**Comment by jeremyfa** [comment]
Got the same problem, even after building and setting again the flow file.

**Comment by prime31** [comment]
I've tried that and myriad other things. Occasionally (maybe 1 in 10 times) it works. With the extra cp command hacked in it has been solid as a rock for me. When I get some time I'll dig in further and see if I can figure out why that extra line isn't getting added automatically for me.

**Comment by ruby0x1** [comment]
@jeremyfa and I figured out why @prime31 thanks for digging, A fix with some other fixes should be up later today sometime, most likely

**Comment by jeremyfa** [comment]
Although we still have to build the project before having access to the `LuxeApp` type, there was a related problem in atom-flow that is now fixed in _master_ with https://github.com/snowkit/atom-flow/commit/65266746c6bf9a451f1079ebd87bb394b3c6ad9d
Should be better with the fix.
