### ISSUE TITLE
--each in hxml (grammar)

### ISSUE THREAD

**Issue by boozook** [snowkit/atom-haxe#50]
![screen shot 2016-01-03 at 13 24 24](https://cloud.githubusercontent.com/assets/888526/12078308/7bffb4d2-b21d-11e5-933d-a4790cb93bd4.png)

Also added [issue for theRemix/language-haxe](https://github.com/theRemix/language-haxe/issues/12)

**Comment by ruby0x1** [comment]
it would be added to the existing grammar at language-haxe
