### ISSUE TITLE
Package spawning process: 'haxe' could not be spawned

### ISSUE THREAD

**Issue by 5290charlie** [snowkit/atom-haxe#52]
## Steps to reproduce:
1. Open Atom Application (OSX)
## Expected Result:
- Atom starts up normally with haxe support
## Actual Result:
- Atom starts up with haxe highlighting (at the least), but triggers error message: " _'haxe' could not be spawned. Is it installed and on your path? If so please open an issue on the package spawning the process._ "
- _haxe is installed and in my path_
## Installed Atom Packages (All packages)
- flow (0.5.3)
- haxe (0.8.10)
- language-haxe (0.3.1)
- linter (1.11.3)
## Other Versions:
- **Atom**: 1.4.3 (same error occurs on Atom 1.5.0-beta3)
- **haxe**: Haxe Compiler 3.2.1
- **haxelib**: Haxe Library Manager 3.2.0-rc.3
- **flow**: 1.0.0-alpha.1

**Comment by 5290charlie** [comment]
Some more digging I found closed issue #47, manually setting the paths to haxe and haxelib have suppressed this error.

**From that issue:**

> Are you on OSX? 
> This is because of how a command is spawned, and on latest osx + latest haxe the full PATH is not loaded meaning it can't find it.

Why is the full PATH not loaded? Is that Atom or OSX?

**Comment by ruby0x1** [comment]
OSX 10.11 changed a bit in that regard. 

There was already a proper fix for this in the plugin, which shouldn't require the explicit path. Your listing doesn't mention which version of the plugin you have installed, is it possible it's not latest or `haxe` isn't in the path? When you run `which haxe` in a _new_ terminal does it list `/usr/local/bin/haxe` or similar?

**Comment by 5290charlie** [comment]
I updated my initial comment with the package versions:
- flow (0.5.3)
- haxe (0.8.10)
- language-haxe (0.3.1)
- linter (1.11.3)

Atom package manager says all packages are up to date. Am I somehow behind in versions and not able to update?

When using `which haxe` (_fresh terminal session_) it is located at `/usr/local/bin/haxe` (`haxelib` is also in `/usr/local/bin/`)

The path(s) `/usr/local/bin/haxe*` are what I added manually to the settings to get it working. So as far as I can tell, the PATH is correctly resolving these from the terminal's perspective, but the Atom package needs the absolute paths to be explicitly defined.

Thanks for the help!

**Comment by vrescobar** [comment]
Hi there,

it happens exactly the same to me, also OSX el Capitan (it seems I have the same setup as 5290charlie) I installed haxe using the official installer and it is as well in the next path: "/usr/local/bin/haxe"

Atom stops complaining when I hardcode its path in the config file: ~/.atom/packages/haxe//lib/haxe-config.js

**Comment by ruby0x1** [comment]
@vrescobar there is a setting in the UI for that under Settings -> Packages -> Haxe btw

![screen 2016-02-17 at 2 30 42 pm](https://cloud.githubusercontent.com/assets/236374/13119320/1a672dd4-d583-11e5-8d06-1664142b0159.png)

**Comment by jeremyfa** [comment]
This should be fixed in latest `0.8.12` release (even without setting executable paths).
