### ISSUE TITLE
After updating to 0.6.0 json coloring is broken

### ISSUE THREAD

**Issue by sercant** [snowkit/atom-haxe#67]
After the recent update, word coloring of json files are broken. I have disabled all my other packages and language-haxe was the one that causing the problem.

language-json version : 0.19.0
atom version : 1.15.0
platform macOS

![image](https://cloud.githubusercontent.com/assets/6319501/24090609/7e5a2d8c-0d4a-11e7-95e7-89c96581dbf1.png)

if I break haxelib-grammars.cson syntax coloring turns back to normal.

**Comment by ruby0x1** [comment]
Hi, I think you meant to file this one at the [language-haxe](https://github.com/theRemix/language-haxe) repo since there is no haxelib-grammar.cson in this repo. This repo handles code completion and build features.

**Comment by sercant** [comment]
I'm terribly sorry for the mistake. As you said i meant to open this issue on [language-haxe](https://github.com/theRemix/language-haxe) repo.

**Comment by ruby0x1** [comment]
no worries!
