### ISSUE TITLE
completion; fix bugs and add type hinting when writing a call signature

### ISSUE THREAD

**Issue by jeremyfa** [snowkit/atom-haxe#8]
What will be done:
- Use the ported type parsing from @jeremyfa
- Add type hinting when writing a call signature
- Handle completion, even when the cursor is not exactly after a dot or a parenthesis

**Comment by jeremyfa** [comment]
Currently polishing completion on anonymous structures as typedef arguments:

![capture d ecran 2015-03-17 a 02 16 10](https://cloud.githubusercontent.com/assets/164094/6684926/08d1328c-cc96-11e4-892e-4835df4bc8a8.png)
![capture d ecran 2015-03-17 a 02 12 56](https://cloud.githubusercontent.com/assets/164094/6684930/0f1964a2-cc96-11e4-8baa-e95eb23735bc.png)

**Comment by nadako** [comment]
wow this is awesome! (btw we were thinking about adding that to the compiler, see https://github.com/HaxeFoundation/haxe/issues/3907)

**Comment by jeremyfa** [comment]
Yeah, that would be great if it's already provided by the compiler!

**Comment by jeremyfa** [comment]
Works now as expected on my side. I close this as any potential problem related to completion should probably be the subject of another issue.
